# Generated by Django 2.0.6 on 2018-11-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20181109_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='semester',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('I-VIII', 'I-VIII')], default='I', max_length=10),
        ),
    ]
