# Generated by Django 2.0.6 on 2018-12-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20181109_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='image_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
