# Generated by Django 2.0.6 on 2018-12-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_announcements_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='date_of_announcement',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
