# Generated by Django 2.1.7 on 2019-03-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20181229_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_organisers',
            field=models.CharField(default='', max_length=200),
        ),
    ]
