# Generated by Django 2.1.4 on 2019-04-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20190315_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_organisers',
        ),
    ]
