# Generated by Django 2.1.7 on 2019-04-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_organisers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_organisers',
            field=models.ManyToManyField(to='events.event_organisers'),
        ),
    ]
