# Generated by Django 2.1.7 on 2019-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20190404_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_organisers',
            field=models.ManyToManyField(blank=True, to='events.event_organisers'),
        ),
    ]
