# Generated by Django 2.1.4 on 2019-04-08 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0023_auto_20190407_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_registere_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=10)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.RemoveField(
            model_name='student_registered_events',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student_registered_events',
            name='event_name',
        ),
        migrations.DeleteModel(
            name='student_registered_events',
        ),
    ]
