# Generated by Django 2.1.7 on 2019-04-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20190409_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_organisers',
            name='event_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
