# Generated by Django 2.1.7 on 2019-04-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_event_organisers_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_organisers',
            name='event_name',
        ),
    ]
