# Generated by Django 2.1.4 on 2019-04-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0016_remove_event_event_organisers'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('events', models.ManyToManyField(to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='studentsignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=25, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(default=' ', max_length=60)),
                ('department_name', models.CharField(choices=[('Dept_1', 'BTECH-CSE'), ('Dept_2', 'BTECH-CIVIL'), ('Dept_3', 'BTECH-MECHANICAL')], default='Dept_1', max_length=70)),
                ('semester', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], default='I', max_length=10)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
    ]
