# Generated by Django 2.0.6 on 2018-07-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180701_1320'),
        ('accounts', '0002_auto_20180707_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='event',
            field=models.ManyToManyField(to='events.event'),
        ),
    ]
