# Generated by Django 2.1.4 on 2019-01-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentsignup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsignup',
            options={'ordering': ['roll_no']},
        ),
    ]
