# Generated by Django 2.1.4 on 2019-01-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190113_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignup',
            name='roll_no',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
