# Generated by Django 2.1.7 on 2019-03-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190113_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsignup',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='studentsignup',
            name='last_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
