# Generated by Django 2.1.4 on 2019-04-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190315_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignup',
            name='email_id',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='studentsignup',
            name='last_name',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='studentsignup',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
