# Generated by Django 2.1.7 on 2019-04-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190403_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='event',
            new_name='events',
        ),
        migrations.AlterField(
            model_name='studentsignup',
            name='email_id',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='studentsignup',
            name='last_name',
            field=models.CharField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='studentsignup',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
